services:
  - type: web
    name: phx2-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn PHx2.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: NODE_VERSION
        value: "20.x"
      - key: PYTHON_VERSION
        value: "3.11.0"
